FROM python:3.7-alpine

RUN mkdir /minitwit-tests

COPY mini-x_tests.py /minitwit-tests/
COPY api_test.py /minitwit-tests/

WORKDIR /minitwit-tests

RUN pip install pytest
RUN pip install requests==2.22.0

EXPOSE 5000

#ENTRYPOINT ["pytest", "-s", "mini-x_tests.py"]
ENTRYPOINT ["sh", "-c", "pytest -s mini-x_tests.py && pytest -s api_test.py"]