FROM python:3.7-alpine

RUN mkdir /minitwit-tests

COPY mini-x_tests.py /minitwit-tests/
COPY api_test.py /minitwit-tests/

WORKDIR /minitwit-tests

RUN sed -i '/REPLACEURL/ c\BASE_URL = "http://mini-x:5000"\' /minitwit-tests/mini-x_tests.py
RUN sed -i '/REPLACEURL/ c\BASE_URL = "http://mini-x:5001"\' /minitwit-tests/api_test.py

RUN pip install pytest
RUN pip install requests==2.22.0

EXPOSE 5000

#ENTRYPOINT ["pytest", "-s", "mini-x_tests.py"]
ENTRYPOINT ["sh", "-c", "pytest -s mini-x_tests.py && pytest -s api_test.py"]