filebeat.inputs:
- type: container
  paths: 
    - '/var/lib/docker/containers/*/*.log'

processors:
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"

- decode_json_fields:
    fields: ["message"]
    target: "json"
    overwrite_keys: true

output.elasticsearch:
  hosts: ["${ES_URL}"]
  protocol: "${ES_PROTOCOL:https}"
  username: "${ES_USERNAME}"
  password: "${ES_PASSWORD}"
  indices:
    - index: "filebeat-mini-x-%{[agent.version]}-%{+yyyy.MM.dd}"
      when.or:
        - contains:
            container.image.name: mini-x
        - contains:
            container.image.name: minix

    - index: "filebeat-postgres-%{[agent.version]}-%{+yyyy.MM.dd}"
      when.contains:
          container.image.name: postgres

    - index: "filebeat-elastic-%{[agent.version]}-%{+yyyy.MM.dd}"
      when.or:
        - contains:
            container.image.name: filebeat
        - contains:
            container.image.name: elasticsearch
        - contains:
            container.image.name: kibana

    - index: "filebeat-proxy-%{[agent.version]}-%{+yyyy.MM.dd}"
      when.equals:
        container.image.name: nginx

logging.json: true
logging.metrics.enabled: false
