name: Publish
on: 
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build and Test
        run: |
          cargo build --verbose

      - name: Generate Release Number
        id: generate_release
        run: echo "RELEASE_VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Zipping files
        run: zip -r "${{ github.ref_name }}-linux-x64.zip" .

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/heads/main')
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          files: |
            *.zip
